#!/usr/bin/env python3
"""Shared packer for the poc_survey flash-resident page assets.

Both served pages (page/survey.html -> PAGE_GZ in page_gz.h, page/cal.html ->
CAL_GZ in cal_page_gz.h) are compile-time C byte arrays served straight from
flash with Content-Encoding: gzip. This module replaces the OLD pipeline
(gzip -> base64 -> PAGE_GZ_B64/CAL_GZ_B64 string inside the .ino ->
decodeB64() into malloc'd RAM at boot / lazily per request), which held
47.4/25.8 KB of heap and produced the mbedtls -0x7F00 SSL_SETUP_FAILED wedge
(resident) plus fragmented-heap contiguity misses on lazy re-decode.

Byte identity: fresh gzip.compress(html, 9) is reproducible byte-for-byte
except the 4-byte MTIME header field (measured 03 Oct 2026). Regeneration is
therefore deterministic with MTIME carried from the currently-served asset,
keeping the flash array byte-identical to what the box has been serving. When
the html changes (no previous asset decompresses equal) MTIME becomes the
pack time.

Header layout (stable so verify_flash_pages.py can diff byte-exact):
  banner comment, include guard, #include <pgmspace.h>,
  static const unsigned NAME_LEN = N;
  static const unsigned char NAME[] PROGMEM = { rows of 16 };
"""
import base64, gzip, io, re, time
from pathlib import Path


def gz_payload(html: bytes, mtime: int) -> bytes:
    """Deterministic gzip -9 (no FNAME field, fixed MTIME)."""
    buf = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=buf,
                       compresslevel=9, mtime=mtime) as g:
        g.write(html)
    return buf.getvalue()


def b64_blob_from_ino(ino_text: str, marker: str):
    """Legacy gz bytes from the old base64 const (e.g. 'PAGE_GZ_B64')."""
    if not marker:
        return None
    m = re.search(re.escape(marker) + r"\[\]\s*=(.*?);\n", ino_text, re.S)
    if not m:
        return None
    try:
        return base64.b64decode("".join(re.findall(r'"([^"]+)"', m.group(1))))
    except Exception:
        return None


def array_from_header(header_text: str, name: str):
    m = re.search(re.escape(name) + r"\[\] PROGMEM = \{(.*?)\};", header_text, re.S)
    if not m:
        return None
    return bytes(int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1)))


def header_len(header_text: str, name: str):
    m = re.search(re.escape(name) + r"_LEN\s*=\s*(\d+)", header_text)
    return int(m.group(1)) if m else None


def emit_header(name: str, gz: bytes, src_rel: str) -> str:
    name2src = {"PAGE_GZ": "page/survey.html", "CAL_GZ": "page/cal.html"}
    name2pack = {"PAGE_GZ": "pack_page.py", "CAL_GZ": "pack_cal_page.py"}
    src = name2src.get(name, src_rel)
    pack = name2pack.get(name, "pack_page.py")
    rows = [gz[i:i + 16] for i in range(0, len(gz), 16)]
    body = "\n".join("  " + ",".join(f"0x{b:02x}" for b in r) + "," for r in rows)
    lines = [
        f"// Auto-generated by {pack} (via the shared page_assets.py module in",
        "// firmware/tools). Compile-time flash asset, replaces the old",
        f"// {name}_B64 base64 string + boot-time base64-decode into malloc'd RAM.",
        f"// Payload = gzip -9 of {src}, served with Content-Encoding: gzip.",
        "// Layout is stable: verify_flash_pages.py regenerates and file-diffs.",
        "",
        f"#ifndef {name}_H",
        f"#define {name}_H",
        "",
        "#include <pgmspace.h>",
        "",
        f"static const unsigned {name}_LEN = {len(gz)};",
        f"static const unsigned char {name}[] PROGMEM = {{",
        body,
        "};",
        "",
        f"#endif // {name}_H",
        "",
    ]
    return "\n".join(lines)


def pack_flash_header(html_path, header_path, name, ino_text: str = "",
                      legacy_marker: str = None):
    """Pack html as a flash array header. Returns (text, html_len, gz_len,
    carried_mtime_or_None). MTIME carry: the served asset (legacy .ino base64
    blob first, then the existing header) whose decompressed bytes == html.
    """
    html = Path(html_path).read_bytes()
    header_path = Path(header_path)
    existing = header_path.read_text() if header_path.exists() else ""
    carried = None
    for src in (b64_blob_from_ino(ino_text, legacy_marker) if legacy_marker else None,
                array_from_header(existing, name)):
        if src is not None and gzip.decompress(src) == html:
            carried = int.from_bytes(src[4:8], "little")
            break
    mtime = carried if carried is not None else int(time.time())
    gz = gz_payload(html, mtime)
    return emit_header(name, gz, ""), len(html), len(gz), carried
